name: get_api_mahasiswa
version: 1.0.0+1
publish_to: none
description: GetApiMahasiswaPPDIKTI
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: ^1.1.0
  webview_flutter: ^4.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

